### ISSUE TITLE
SSR Example

### ISSUE THREAD

**Issue by robhicks** [WebReflection/uce#13]
the uce - lit-html comparison identifies SSR as a key feature of uce. Is there a SSR example somewhere?

**Comment by WebReflection** [comment]
The lit-what? You can land templates on the server, these can either autoload files (there are example) or bootstrap live on the page, it’s like a declarative shadow DOM compatible with PHP or anything else, it’s SSR by default, and it has literally nothing to do with lit.

**Comment by robhicks** [comment]
Perhaps you have forgotten this [comparison](https://gist.github.com/WebReflection/ae3451c17c5e882bbc7f0714c14eefcd) where you state that uce supports SSR while lit-html's support for SSR is questionable. 

But from your dismissive response,  I must assume you don't care about developers considering uce for SSR. Accordingly, I won't bother.

**Comment by WebReflection** [comment]
@robhicks I actually read *companion* instead of *comparison* (just read it again to be sure) and thought you were trolling ... but yeah, this project is 100% SSR, every example is about presenting components on the HTML, with optional lazy load for their definitions, so I am not sure what you are asking. This project is born SSR: you write components definitions in a `<template is="uce-template">` and that's it.

[Life Diary](https://github.com/WebReflection/life-diary#readme) is 100% NodeJS driven and based on *uce-components* ... would that help? or better ... what are you asking? maybe I don't get it.

**Comment by robhicks** [comment]
@WebReflection sorry for the confusion. Life Diary is exactly what I needed to better understand SSR with uce. Thanks!

**Comment by WebReflection** [comment]
@robhicks no I am sorry for misreading your comment ... but if there's anything in particular you'd like to see as example that is not a giant project, I'd be more than happy to create one and publish it somewhere (lambda or the like).

**Comment by robhicks** [comment]
@WebReflection thianks for the response! Have you looked at either [vite](https://vitejs.dev/) or [snowpack](https://www.snowpack.dev/)? Both support SSR (and serverless) with an incredible developer experience. I wonder if it might be worth your time to look at one or both of them and show how to configure them for your code.
